web:
    image: nginx:stable
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./web:/var/www/html
        - ./nginx/conf/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
        - ./nginx/conf/fastcgi.conf:/etc/nginx/fastcgi.conf
        - ./nginx/sites:/etc/nginx/conf.d
    links:
        - php

php:
    build: ./php
    dockerfile: Dockerfile
    volumes:
        - ./web:/var/www/html
    environment:
        DB_HOST: "db"
    links:
        - db

db:
    image: mariadb:latest
    ports:
        - "3306:3306"
    volumes:
        - ./mariadb/.data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root_secret_passwd
        MYSQL_DATABASE: dbdata
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbpasswd
